### Test Backend
GET http://localhost:8081/test

### Create User
POST http://localhost:8081/api/users
Content-Type: application/json

{
    "email": "test@example.com",
    "firstName": "John",
    "lastName": "Doe"
}

### Get User
GET http://localhost:8081/api/users/1